### PR TITLE
Take given guard into account when fetching currently authenticated user

### PR DESCRIPTION
**Pull request by JapSeyz**
Take given guard into account when fetching currently authenticated user

### CODE REVIEW

**Comment by JapSeyz** [comment]
Not entirely sure why PHPStan throws a fit over Auth::guard() but not Auth::login(). However it should be fixed by importing the Auth Facade

**Comment by fabio-ivona** [comment]
> Not entirely sure why PHPStan throws a fit over `Auth::guard()` but not `Auth::login()`. However it should be fixed by importing the Auth Facade

first of all: thanks for contributing!

yep, I see

but I think now it would trigger another error, because Auth could return null

**Comment by fabio-ivona** [comment]
> PHPStan throws a fit over Auth::guard() but not Auth::login()

btw this is a strange behaviour, I'll disscuss this with the guys that work on larastan

**Comment by JapSeyz** [comment]
> > Not entirely sure why PHPStan throws a fit over `Auth::guard()` but not `Auth::login()`. However it should be fixed by importing the Auth Facade
> 
> first of all: thanks for contributing!
> 
> yep, I see
> 
> but I think now it would trigger another error, because Auth could return null

Still curious how it would pass before; as `Auth::login()` could also return null.

I mean, the return of `Auth::guard()->login()` and `Auth::login()` should be identical, as `Auth::login()` is just syntastic sugar for `Auth::guard(null)->login()`

**Comment by JapSeyz** [comment]
> > PHPStan throws a fit over Auth::guard() but not Auth::login()
> 
> btw this is a strange behaviour, I'll disscuss this with the guys that work on larastan

That's fine, we can wait with merge until it's cleared up.

**Comment by fabio-ivona** [comment]
> That's fine, we can wait with merge until it's cleared up.

I think the current behaviour is the right one, we could add another assertion that handles the guest case

```php
 $authenticated = Auth::user();
        
assertNotNull($authenticated, "No user is currently authenticated");
assertEquals($this->value->id, $authenticated->id, "The User ID #{$this->value->id} doesn't match authenticated User ID #$authenticated->id");

```

what do you think?

**Comment by JapSeyz** [comment]
> > That's fine, we can wait with merge until it's cleared up.
> 
> I think the current behaviour is the right one, we could add another assertion that handles the guest case
> 
> ```
>  $authenticated = Auth::user();
>         
> assertNotNull($authenticated, "No user is currently authenticated");
> assertEquals($this->value->id, $authenticated->id, "The User ID #{$this->value->id} doesn't match authenticated User ID #$authenticated->id");
> ```
> 
> what do you think?

I am unsure what you mean?

The `bug`? I am trying to fix, is if you're using a custom guard.
Eg. having two different logins;  an internal and a public login that use different guards.

This code will always fail, because it'll try to fetch the user from the `web` guard,
```php
/** @var PublicUser $user */
expect($user)->toBeAuthenticated('public-guard')
```

It isn't about checking for the user being a guest.
I hope that makes sense?

**Comment by fabio-ivona** [comment]
sorry, my fault, copied the old code when adding my fix:

I meant to only adding an assertion to check the authenticatable is not null

```php
        $authenticated = Auth::guard($guard)->user();
        assertNotNull($authenticated, "No user is currently authenticated");

        /** @phpstan-ignore-next-line  */
        assertEquals($this->value->id, $authenticated->id, "The User ID #{$this->value->id} doesn't match authenticated User ID #$authenticated->id");

```

**Comment by JapSeyz** [comment]
> sorry, my fault, copied the old code when adding my fix:

Yeah, that looks great!

Still not entirely sure how `$authenticated = Auth::user();` passed PHPStan before, while `$authenticated = Auth::guard($guard)->user();` doesn't.

either way ```php
$authenticated = Auth::guard($guard)->user();
assertNotNull($authenticated, "No user is currently authenticated");
```

is the correct solution

**Comment by fabio-ivona** [comment]
> Still not entirely sure how `$authenticated = Auth::user();` passed PHPStan before, while `$authenticated = Auth::guard($guard)->user();` doesn't.

yep, that's weird

I've written to can vural and nuno maduro, let's see what they think

**Comment by JapSeyz** [comment]
> > Still not entirely sure how `$authenticated = Auth::user();` passed PHPStan before, while `$authenticated = Auth::guard($guard)->user();` doesn't.
> 
> yep, that's weird
> 
> I've written to can vural and nuno maduro, let's see what they think

Sweet, want me to adapt my PR to the code suggested, or want to do it yourself?

**Comment by fabio-ivona** [comment]
you can do it, thanks!

**Comment by JapSeyz** [comment]
If PHPStan fails again, we can force it with `/** @var \Illuminate\Contracts\Auth\Authenticatable $user */` below the null check.

**Comment by JapSeyz** [comment]
Not entire sure whether or not it should be `with guard $guardName` or `on guard $guardName`, or something entirely different. Got any preference?

**Comment by JapSeyz** [comment]
My mistake, I need the function import too

**Comment by fabio-ivona** [comment]
> If PHPStan fails again, we can force it with `/** @var \Illuminate\Contracts\Auth\Authenticatable $user */` below the null check.

that's fine for me

also, "with" guard sounds good

**Comment by JapSeyz** [comment]
> > If PHPStan fails again, we can force it with `/** @var \Illuminate\Contracts\Auth\Authenticatable $user */` below the null check.
> 
> that's fine for me
> 
> also, "with" guard sounds good
> 
> remember to run `composer lint` to fix the code style 😉

Yup, just been doing it through the GH web UI, as it seemed like a quick-fix.

I'll pull it down and lint it real quick. Apologies

**Comment by JapSeyz** [comment]
Struggling a bit with the `phpdoc_to_comment` fix, wanting to covert 
```php
  /**
   * @var \Illuminate\Contracts\Auth\Authenticatable $authenticated
   * @var \Illuminate\Contracts\Auth\Authenticatable $this->value
   */
```

```php
  /*
   * @var \Illuminate\Contracts\Auth\Authenticatable $authenticated
   * @var \Illuminate\Contracts\Auth\Authenticatable $this->value
   */
```
which removes the DocBloc property of it, and makes PHPStan fail. Have you faced a similar issue previously?

**Comment by fabio-ivona** [comment]
I just noticed the assertAuthenticated  on line 20 :facepalm: 

so we can safely do

```php
assertAuthenticated($guard);

/** @var \Illuminate\Contracts\Auth\Authenticatable $authenticated */
$authenticated = Auth::guard($guard)->user();

assertEquals($this->value->id, $authenticated->id, "The User ID #{$this->value->id} doesn't match authenticated User ID #$authenticated->id");

```

**Comment by JapSeyz** [comment]
> I just noticed the assertAuthenticated on line 20 🤦

🤦 didn't notice either...

I've ignored the line, as `Authenticatable` doesn't have an `id` prop, and `getAuthIdentifier()` returns mixed, which PHPStan won't allow to be converted into a string.

So lots of weird behaviour unfortunately, but it should be linted and tested now.

**Comment by JapSeyz** [comment]
Thanks for being so responsive, and for the package :)

**Comment by fabio-ivona** [comment]
all seems ok! Thanks @JapSeyz !

will release a patch right now

**Comment by JapSeyz** [comment]
Awesome, I'll test it in my suite later tonight!

Thanks

**Comment by JapSeyz** [comment]
It works beautifully now 🎉 

Thank you!

**Pull request merged**
